/home/mtx/data/tide/outdata/tides00/halo/smooth1.25/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/tides00/halo/smooth1.25/PS_KK
/home/mtx/github/Tide/src/TIDES.py:112: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/tides00/0.000halo00.bin
/home/mtx/data/tide/outdata/tides00/halo/smooth1.25/
Loading data.................
Smoothing....................
Smoothing..................OK
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/tides00/halo/smooth1.25/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/tides00/halo/smooth1.25/PS_KK
/home/mtx/data/tide/outdata/tides00/halo/smooth1.25/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
/home/mtx/data/tide/outdata/tides00/test/smooth1.25/0.000den00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/tides00/test/smooth1.25/PS_KK
/home/mtx/github/Tide/src/TIDES.py:112: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/tides00/0.000den00.bin
/home/mtx/data/tide/outdata/tides00/test/smooth1.25/
Loading data.................
Smoothing....................
Smoothing..................OK
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/tides00/den/smooth1.25/0.000den00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/tides00/den/smooth1.25/PS_KK
/home/mtx/data/tide/outdata/tides00/test/smooth1.25/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14526,1],8]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError:     fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14514,1],2]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
IOError: unable to open file (File accessibilty: Unable to open file)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError:     fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14518,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError:     fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin1d.py", line 18, in <module>
    f=h5py.File(filename1,'r')#'/home/mtx/data/tide/outdata/old_test/0.000den00_Pk_kappa_delta.hdf5')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14506,1],16]
  Exit code:    1
--------------------------------------------------------------------------
step 2 ok
